Sync with Faust commit 0dc0a21b2cab4d575238d54353b37decdb4646c3. Improved rfaust

diff --git a/cloud-tests/rfaust b/cloud-tests/rfaust
--- a/cloud-tests/rfaust
+++ b/cloud-tests/rfaust
@@ -3,6 +3,8 @@
 #USAGE : rfaust <servurl> ==> <targets>
 #USAGE : rfaust <servurl> <platform> <arch> <srcfile> ==> <binary.zip>
 
+URL="34.76.156.75"
+
 function targetrequest {
     curl  "$1/targets"
 }
@@ -12,8 +14,18 @@ function compilation {
 }
 
 
-if [ "$#" == "1" ]; then
+if [ "$#" == "0" ]; then
+    targetrequest "$URL"
+elif [ "$#" == "1" ]; then
     targetrequest "$1"
+elif [ "$#" == "3" ]; then
+    if [ -f "$3" ]; then
+        rm -rf binary.zip
+	    compilation $URL $1 $2 $3
+    else 
+        echo "ERROR: file $3 doesn't exist"
+        exit 1
+    fi
 elif [ "$#" == "4" ]; then
     if [ -f "$4" ]; then
         rm -rf binary.zip
@@ -23,6 +35,6 @@ elif [ "$#" == "4" ]; then
         exit 1
     fi
 else
-    echo "usage : $0 <servurl> [<platform> <arch> <srcfile>]"
+    echo "usage : $0 [<servurl>] [<platform> <arch> <srcfile>]"
 fi 
 
